name: AcropolisBorders
description: $description
version: '${version}'

main: me.nikhildasgupta.acropolisBorders.AcropolisBorders
api-version: '26.1'

authors: [ YellowLion11500 ]
website: https://acropolis-smp.co.uk
depend: [squaremap]